name: flutter_test_helios
description: "A new Flutter project."
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  logger: ^2.2.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  graphql: ^5.2.0-beta.7
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  graphql_codegen: ^0.14.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
